# Generated by Django 5.2.17 on 2026-08-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('portrait', models.ImageField(blank=True, upload_to='')),
                ('instagram_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('hero_background', models.ImageField(blank=True, upload_to='')),
                ('hero_foreground_object', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
