# Generated by Django 5.2.17 on 2026-08-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_photographer'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='hero_portrait',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
